### ISSUE TITLE
Design PCB

### ISSUE THREAD

**Issue by David-Estevez** [UC3Music/PolyTuna#1]
Steps:

* [x] Design schematic in Kicad
  * [x] Add old design
  * [x] Make required modifications
  * [x] Check new input stage
  * [x] Add DC-DC Conversor
  * [x] Check Teensy Board Connections
  * [x] Add AP7313
  * [x] Add 3 buttons to implement weird things
  * [x] Add 3 pots to implement weird things
  * [x] Add a jack output from SGTL5000 to implement weird things
  * [x] Add some LEDs to know when the weird things are ON/OFF
  * [x] Add SDA/SCL ports for the display
  * [x] Add some 3.3V and 5V extra ports
* [x] Select components / footprints
* [x] Design PCB
* [x] Double-check PCB
* [x] Triple-check PCB
* [x] Manufacture PCB

**Comment by SerjSanchez** [comment]
* [x] Drummer with metronome.

**Comment by JorFru** [comment]
- [x] Double check jack footprint on the good side of PCB.
- [x] Double check if any component can block a connector, wire, etc.

**Comment by SerjSanchez** [comment]
On production!!!
