### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by SerjSanchez** [UC3Music/PolyTuna#3]
* [x] Decide input stage values for resistors
* [x] Buy components

**Comment by David-Estevez** [comment]
Added BOM with required components (c6ac7de45cbd0cc7031ab835b28889445f510f84). Prices and references will be updated with final values when components have been bought.

**Comment by David-Estevez** [comment]
I already bought the components and they have just arrived. Should I close this one?

**Comment by SerjSanchez** [comment]
Yup
